
drop table if exists competition cascade;

create table competition (
    competition_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

INSERT INTO competition (name) VALUES ('Hudson');
INSERT INTO competition (name) VALUES ('Long Island');

drop table if exists team cascade;

create table team (
    team_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num int,
    name varchar(100)
);

insert into team (num, name) values ('1796', 'RoboTigers');

drop table if exists match;

create table match (
    match_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id int references competition(competition_id) NOT NULL,
    team_id int references team(team_id) NOT NULL,
    match_num int NOT NULL,
    last_modified timestamp(0) NOT NULL DEFAULT (now())::timestamp(0),
    CONSTRAINT match_composite_key UNIQUE (competition_id, team_id, match_num)
);